// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8Jm3LTkn5ivM4m3ijekesCmAEcZJkX3M',
    appId: '1:518291877749:web:ecba936d74ec55922e6d3c',
    messagingSenderId: '518291877749',
    projectId: 'examenmtc',
    authDomain: 'examenmtc.firebaseapp.com',
    storageBucket: 'examenmtc.firebasestorage.app',
    measurementId: 'G-6HZCPCNMCD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5P_TUJdSpNXkUijVYjvDu4B3FlXh0e10',
    appId: '1:518291877749:android:a1d4f61a696103c02e6d3c',
    messagingSenderId: '518291877749',
    projectId: 'examenmtc',
    storageBucket: 'examenmtc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXaLNL_a6pTt4gvTbrSUbfsH6tF6G9Xt8',
    appId: '1:518291877749:ios:6c9351dab62b71dd2e6d3c',
    messagingSenderId: '518291877749',
    projectId: 'examenmtc',
    storageBucket: 'examenmtc.firebasestorage.app',
    iosBundleId: 'com.example.examenMtc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXaLNL_a6pTt4gvTbrSUbfsH6tF6G9Xt8',
    appId: '1:518291877749:ios:6c9351dab62b71dd2e6d3c',
    messagingSenderId: '518291877749',
    projectId: 'examenmtc',
    storageBucket: 'examenmtc.firebasestorage.app',
    iosBundleId: 'com.example.examenMtc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8Jm3LTkn5ivM4m3ijekesCmAEcZJkX3M',
    appId: '1:518291877749:web:623285ea83fdd1d12e6d3c',
    messagingSenderId: '518291877749',
    projectId: 'examenmtc',
    authDomain: 'examenmtc.firebaseapp.com',
    storageBucket: 'examenmtc.firebasestorage.app',
    measurementId: 'G-5L5F3MNJ89',
  );

}